# Build Settings
title: DotNetEvolved
subtitle: Development Blog
twitter_username: joshuagarrison7
github_username: binarynexus
repository:  JoshuaGarrison27/JoshuaGarrison27.github.io 
search: true

# More Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: air
# Outputting
permalink: /:year/:month/:day/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Joshua Garrison"
  avatar : "/assets/images/bio-photo.png"
  bio    : My name is Joshua and I have been coding for over 15 years. This blog is a way for me to share my thoughts and findings while on my coding adventures.
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://dotnetevolved.com/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/JoshuaGarrison7"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JoshuaGarrison27"
    - label: LinkedIn
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/joshuacgarrison"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/JoshuaGarrison7"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JoshuaGarrison27"
    - label: LinkedIn
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/joshuacgarrison"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
